{% set name = "tomviz" %}
{% set version = "2.1.0" %}
{% set paraview_version = "v6.0.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/OpenChemistry/tomviz
    git_rev: {{ version }}
    folder: tomviz
  # Submodules updated in build.sh: pybind11

  - git_url: https://gitlab.kitware.com/paraview/paraview.git
    git_rev: {{ paraview_version }}
    folder: paraview
  # Submodules updated in build.sh: VTK, VisItBridge, QtTesting, catalyst

build:
  number: 0
  # Skip windows for now, until we fix the build for it
  skip: true  # [win]

requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - libgl-devel  # [linux]
    - libegl-devel  # [linux]
    - libglvnd-devel  # [linux]
    - qt6-main >=6.9.3
    - libprotobuf
    - cgns
    - libboost-headers
    - libzip
    - libcurl
    - icu
    - libharu
    - libxml2-devel 2.14*
    - tbb-devel
  run:
    - python
    - numpy
    - scipy
    - marshmallow
    - jsonpatch
    - jsonpointer
    - pyfftw
    - pygments
test:
  imports:
    - paraview
    - paraview.simple
    - paraview.numpy_support

about:
  home: https://github.com/OpenChemistry/tomviz
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - tomviz/LICENSE
  summary: 'Cross platform, open source application for the processing, visualization, and analysis of 3D tomography data'
  doc_url: https://tomviz.readthedocs.io/
  dev_url: https://github.com/OpenChemistry/tomviz

extra:
  recipe-maintainers:
    - cjh1
    - psavery
    - conda-forge/event-model
